### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-statement-import#126]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_bank_statement_import_camt_oca - ~~By @astirpe - #134~~ By @MaxyMoos - #158 
- [x] account_bank_statement_import_move_line - By @gittusr - #167 
- [x] account_bank_statement_import_mt940_base - By @feketemihai - #137 
- [ ] account_bank_statement_import_mt940_nl_ing
- [ ] account_bank_statement_import_mt940_nl_rabo
- [x] account_bank_statement_import_ofx - By @njeudy - #142 
- [x] account_bank_statement_import_qif - By @pedrobaeza - #129 
- [ ] account_bank_statement_import_save_file
- [ ] base_bank_account_number_unique

**Comment by astirpe** [comment]
account_bank_statement_import_camt https://github.com/OCA/bank-statement-import/pull/134

**Comment by njeudy** [comment]
@pedrobaeza : account_bank_statement_import_ofx #142

**Comment by emagdalenaC2i** [comment]
account_bank_statement_import_camt is actually named account_bank_statement_import_camt_oca
Please, could you move up account_bank_statement_import_move_line in the list so that it is sorted correctly in alphabetical order

**Comment by ecino** [comment]
account_bank_statement_import_camt_details #259
