### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-statement-import#40]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] ~~account_bank_statement_import~~ - Removed as already included in v9
- [ ] account_bank_statement_import_mt940_nl_ing
- [ ] account_bank_statement_import_save_file
- [x] account_bank_statement_import_qif - By @pedrobaeza - #81 
- [ ] account_bank_statement_import_mt940_nl_rabo
- [ ] account_bank_statement_import_mt940_base
- [ ] account_bank_statement_import_ofx - https://github.com/OCA/bank-statement-import/pull/44
- [x] account_bank_statement_import_camt - By @hbrunn - #79 
- [ ] base_bank_account_number_unique
