### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-statement-import#503]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_bank_statement_clear_partner
- [x] account_bank_statement_import_online_qonto - By @carolinafernandez-tecnativa - #682
- [x] account_bank_statement_import_qif - By @victoralmau - #681
- [x] account_statement_import_base - By @alexis-via - #550
- [x] account_statement_import_camt - By @sonhd91 - #556
- [x] account_statement_import_camt54 - By @sonhd91 - #562
- [x] account_statement_import_file - By @alexis-via - #575 :warning: renamed
- [x] account_statement_import_file_reconciliation_widget - By @alexis-via - #576 :warning: renamed
- [x] account_statement_import_online - By @NL66278 - #548
- [x] account_statement_import_online_gocardless - By @njeudy - #667
- [x] account_statement_import_online_paypal - By @stefan-tecnativa - #630
- [x] account_statement_import_online_ponto - By @NL66278 - #554
- [x] account_statement_import_txt_xlsx - By @victoralmau - #628

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by alexis-via** [comment]
Reminder : account_statement_import should be renamed account_statement_import_file in v16

**Comment by sonhd91** [comment]
* `account_statement_import_file`: #535

**Comment by sonhd91** [comment]
`account_statement_import_camt` : #556

**Comment by pegonzalezs** [comment]
working on account_statement_import_camt54

**Comment by alexis-via** [comment]
About the migration of bank statement import to v16:
I see that the form view of account.bank.statement has been removed in the "account" module cf https://github.com/odoo/odoo/blob/16.0/addons/account/views/account_bank_statement_views.xml There is only tree, pivot and graph view. All the views of account.bank.statement.line were removed.

@etobella  has made a great work on account_reconcile_oca (the replacement of account_reconciliation_widget) in this v16 PR https://github.com/OCA/account-reconcile/pull/500  He restored the views of account.bank.statement.line.

I suppose that the idea of Odoo SA was to have only the JS interface to view bank statements. Up to v15, we had the 2 interfaces:
- JS interface used to "process" the bank statement
- traditional interface to "view" the bank statement, verify data, view underlying account.move
In v16, is it a good idea to have just the JS interface ? I see that the JS interface of v16 allows to view the processed bank statement lines and view the underlying account.move.
I must say that, from a new user point of view, having just one interface make it easier to understand. The only remaining argument for a traditional form view of account.bank.statement is debugging/verification purposes ? Are there other arguments?

**Comment by pedrobaeza** [comment]
What more to debug/verify that is not in that view?

**Comment by florian-dacosta** [comment]
@sonhd91 Could you make  the PR about account_statement_import_file even if it is WIP ?

**Comment by sonhd91** [comment]
> @sonhd91 Could you make the PR about account_statement_import_file even if it is WIP ?

Sorry for the wait, please check it out 
* `account_statement_import_file`: WIP #535

**Comment by zaoral** [comment]
Hi!
We will be working on migration of account_statement_import_txt_xlsx module https://github.com/OCA/bank-statement-import/pull/559
Please add it to module list.

Best Regards

**Comment by sonhd91** [comment]
`account_statement_import_camt54`: #562
