### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-statement-import#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] ~~account_bank_statement_import_base~~ - Removed as already included in v9
- [x] account_bank_statement_import_camt - By @StefanRijnhart - #84
- [x] account_bank_statement_import_mt940_base - By @astirpe - #125 
- [ ] account_bank_statement_import_mt940_nl_ing
- [ ] account_bank_statement_import_mt940_nl_rabo
- [x] account_bank_statement_import_ofx - By @alexis-via - #80 
- [x] account_bank_statement_import_qif - By @seb4itik - #92
- [ ] account_bank_statement_import_save_file
- [ ] base_bank_account_number_unique

**Comment by astirpe** [comment]
account_bank_statement_import_mt940_base: https://github.com/OCA/bank-statement-import/pull/125

**Comment by melroy89** [comment]
Ow Ow, I really hopen this kind of basic features were part of OCA. But i am mistaken 😢,dissapointed.

And soon v11 will even be released..

**Comment by pedrobaeza** [comment]
What are you talking about?

**Comment by melroy89** [comment]
Is it possible to import multiple bank transactions at once with OCA? Although manually..

Moreover, with OCA I don't get any supported file format. Nothing works.. Even CSV is apparently not supported, or do I miss something? I tried CSV comma, CSV semicon and SWIFT-MT940 format.

So basically, when I try to import something. It says: supported import types: [none]?

![no_import_types](https://user-images.githubusercontent.com/628926/31050687-bfcd97b2-a652-11e7-84d9-c384efd08977.png)

I'm using Odoo 10.0-20170930

**Comment by pedrobaeza** [comment]
Well, this is not something to be put here, as this is for tracking the migration, but it seems that you haven't installed the migrated module, which is still in the PR: #125

**Comment by melroy89** [comment]
@pedrobaeza Thanks for the heads-up. I just installed the default Odoo v10 installation with Accounting module (which includes this module by default).

I didn't know I needed to do more. Sorry.

**Comment by melroy89** [comment]
Is it correct, that this base module doesn't show up in the file type supported list? I have 'SNS Bank', so I think ING or Rabobank won't help here.. Furthermore I think ING/Rabo is not yet ready for v10/v11.

I do see this now:
![only_import_types](https://user-images.githubusercontent.com/628926/31051220-c7f5b11c-a662-11e7-978e-618ba8038b2d.png)

The problem with MT940 is that each bank can implements it's own standard, in my eyes MT940 could therefor not even be called a standard. Nevertheless, did you put SNS bank MT940 also on the TODO list? I'm currently asking them if there MT940 format is the same as ING or Rabobank:
https://forum.snsbank.nl/mijn-sns-sns-mobiel-bankieren-app-69/downloaden-in-ofx-formaat-niet-meer-mogelijk-7752

**Comment by StefanRijnhart** [comment]
@danger89 can't you download Camt.053 for your SNS account? It should be a perfectly good replacement for all the bank specific CSV and MT940 formats.

**Comment by melroy89** [comment]
@StefanRijnhart not that I know of. Maybe I should ask SNS. So Camt.053 is supported by OCA v10 (EDIT: ah I see you are busy with that PR)?

![export_sns](https://user-images.githubusercontent.com/628926/31055792-8e034472-a6c8-11e7-8766-a14afdd39ff7.png)

**Comment by StefanRijnhart** [comment]
@danger89 the Camt PR was ready in December 2016, and merged sometime later ;-)

Yes, ask your bank. The format is listed in the business account manual of SNS. You can download it here: https://www.snsbank.nl/zakelijk/zakelijk-betalen/mijn-sns-zakelijk.html. It says you have to register to be able to use it.

**Comment by melroy89** [comment]
Ow, I currently try it with my personal bank account (iso business account) , but I still will ask it. Thx!
